In [17]:
import geopandas as gpd
import matplotlib.pyplot as plt

rivers_poly = gpd.read_file("jamuna_polygon.geojson")
rivers_line = gpd.read_file("jamuna.geojson")

rivers_poly.crs
rivers_line.crs

<Geographic 2D CRS: EPSG:4326>
Name: WGS 84
Axis Info [ellipsoidal]:
- Lat[north]: Geodetic latitude (degree)
- Lon[east]: Geodetic longitude (degree)
Area of Use:
- name: World.
- bounds: (-180.0, -90.0, 180.0, 90.0)
Datum: World Geodetic System 1984 ensemble
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

In [18]:
rivers_poly.total_bounds

array([88.64872738, 26.28015367, 88.71968359, 26.4997126 ])

In [7]:
gpd.GeoSeries([],crs="EPSG:4326").crs

<Geographic 2D CRS: EPSG:4326>
Name: WGS 84
Axis Info [ellipsoidal]:
- Lat[north]: Geodetic latitude (degree)
- Lon[east]: Geodetic longitude (degree)
Area of Use:
- name: World.
- bounds: (-180.0, -90.0, 180.0, 90.0)
Datum: World Geodetic System 1984 ensemble
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

In [19]:
rivers_poly.geometry.area

C:\Users\user\AppData\Local\Temp\ipykernel_18048\3014518664.py:1: UserWarning: Geometry is in a geographic CRS. Results from 'area' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  rivers_poly.geometry.area

0    0.000104
dtype: float64

In [24]:
rivers_poly_projected=rivers_poly.to_crs("EPSG:32645")

rivers_line_projected=rivers_line.to_crs("EPSG:32645")

In [25]:
rivers_poly_projected.crs

<Projected CRS: EPSG:32645>
Name: WGS 84 / UTM zone 45N
Axis Info [cartesian]:
- E[east]: Easting (metre)
- N[north]: Northing (metre)
Area of Use:
- name: Between 84°E and 90°E, northern hemisphere between equator and 84°N, onshore and offshore. Bangladesh. Bhutan. China. India. Kazakhstan. Mongolia. Nepal. Russian Federation.
- bounds: (84.0, 0.0, 90.0, 84.0)
Coordinate Operation:
- name: UTM zone 45N
- method: Transverse Mercator
Datum: World Geodetic System 1984 ensemble
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

In [26]:
rivers_line_projected.crs

<Projected CRS: EPSG:32645>
Name: WGS 84 / UTM zone 45N
Axis Info [cartesian]:
- E[east]: Easting (metre)
- N[north]: Northing (metre)
Area of Use:
- name: Between 84°E and 90°E, northern hemisphere between equator and 84°N, onshore and offshore. Bangladesh. Bhutan. China. India. Kazakhstan. Mongolia. Nepal. Russian Federation.
- bounds: (84.0, 0.0, 90.0, 84.0)
Coordinate Operation:
- name: UTM zone 45N
- method: Transverse Mercator
Datum: World Geodetic System 1984 ensemble
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

In [29]:
rivers_poly.total_bounds

array([88.64872738, 26.28015367, 88.71968359, 26.4997126 ])

In [30]:
rivers_poly_projected.total_bounds

array([ 664313.19961224, 2907845.87754765,  671657.68592515,
       2932081.46928035])

In [32]:
rivers_poly_projected["Area_m2"]=(
    rivers_poly_projected.geometry.area
)

rivers_poly_projected["Area_km2"]=(
    rivers_poly_projected["Area_m2"]/1_000_000
)

rivers_poly_projected[
    ["rivname","Area_m2","Area_km2"]
]

  rivname       Area_m2  Area_km2
0    None  1.147935e+06  1.147935

In [ ]:
# Task-1
#calculate the jamuna river length in meter

#store the results in a new column called length_m

In [ ]:
#Task-2
#Convert length_m into kilometers
#create a new column called "length_km"

In [36]:
rivers_line_projected["Length_m"] = (
    rivers_line_projected.geometry.length
)

In [37]:
rivers_line_projected["Length_km"] = (
    rivers_line_projected["Length_m"] / 1000
)

# Display the results
rivers_line_projected[
    ["rivname", "Length_m", "Length_km"]
]

  rivname      Length_m  Length_km
0  Jamuna  41275.320958  41.275321